name: Vocali Backend Develop Deployment

env:
  NODE_OPTIONS: --max-old-space-size=6144

on:
  push:
    branches: [develop]
    paths: ['backend/**']
  workflow_dispatch:

jobs:
  deploy_backend_develop:
    name: Deploy backend develop branch
    runs-on: ubuntu-24.04
    environment: develop
    container:
      image: python:latest
    steps:
      - run: apt-get update
      - run: apt-get install curl git-all zip -y
      - run: pip install awscli
      - uses: actions/checkout@v4

      - name: Copy .env for backend
        working-directory: ./backend
        run: echo "${{ vars.BACKEND_ENV }}" >> .env

      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.1

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install --only=production

      - name: Run backend tests
        working-directory: ./backend
        run: npm test
        env:
          NODE_ENV: test
          SUPABASE_URL: ${{ vars.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ vars.SUPABASE_SERVICE_KEY }}
          JWT_SECRET: ${{ vars.JWT_SECRET }}

      - name: Set AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ vars.AWS_ACCESS_KEY_ID }} &&
          aws configure set aws_secret_access_key ${{ vars.AWS_SECRET_ACCESS_KEY }} &&
          aws configure set region ${{ vars.AWS_DEFAULT_REGION }}

      - name: Create deployment package
        run: |
          cd backend
          zip -r ../vocali-backend-$(date +%Y%m%d-%H%M%S).zip . \
            -x "node_modules/*" ".git/*" "uploads/*" "temp/*" "*.log" "coverage/*"
          cd ..

      - name: Upload to S3 for deployment
        run: |
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          aws s3 cp vocali-backend-$TIMESTAMP.zip s3://${{ vars.S3_DEPLOYMENT_BUCKET }}/vocali-backend-$TIMESTAMP.zip
          echo "Package uploaded: vocali-backend-$TIMESTAMP.zip"

      # Opción adicional: Deploy directo a EC2 usando CodeDeploy
      - name: Trigger CodeDeploy (if configured)
        run: |
          if [ -n "${{ vars.CODEDEPLOY_APPLICATION }}" ]; then
            TIMESTAMP=$(date +%Y%m%d-%H%M%S)
            aws deploy create-deployment \
              --application-name ${{ vars.CODEDEPLOY_APPLICATION }} \
              --deployment-group-name ${{ vars.CODEDEPLOY_GROUP }} \
              --s3-location bucket=${{ vars.S3_DEPLOYMENT_BUCKET }},key=vocali-backend-$TIMESTAMP.zip,bundleType=zip \
              --description "Auto deployment from GitHub Actions - develop branch"
          else
            echo "CodeDeploy not configured, manual deployment required"
          fi

      - name: Deployment complete
        run: |
          echo "🚀 Backend deployment package created successfully!"
          echo "📦 Package location: s3://${{ vars.S3_DEPLOYMENT_BUCKET }}"
          echo "📡 Monitor deployment in AWS Console or EC2 instance"
          echo "🔍 Check logs: ssh to EC2 and run 'pm2 logs vocali-backend'"
