name: Vocali Backend Develop Deployment

env:
  NODE_OPTIONS: --max-old-space-size=6144

on:
  push:
    branches: [develop]
    paths: ['backend/**']
  workflow_dispatch:

jobs:
  deploy_backend_develop:
    name: Deploy backend develop branch
    runs-on: ubuntu-24.04
    environment: develop
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: './backend/package-lock.json'

      - name: Install backend dependencies (including dev)
        working-directory: ./backend
        run: npm ci

      - name: Run backend tests
        working-directory: ./backend
        run: npm test
        env:
          NODE_ENV: test
          SUPABASE_URL: ${{ vars.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ vars.SUPABASE_SERVICE_KEY }}
          JWT_SECRET: ${{ vars.JWT_SECRET }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY || 'test-key-for-ci' }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_S3_BUCKET: 'test-bucket'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Install production dependencies for package
        working-directory: ./backend
        run: |
          # Limpiar node_modules y reinstalar solo producción para el package
          rm -rf node_modules
          npm ci --only=production

      - name: Create deployment package
        run: |
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          echo "Creating package with timestamp: $TIMESTAMP"
          echo "Current directory: $(pwd)"

          # Crear el package directamente con tar (más confiable que zip)
          echo "Creating deployment package with tar..."
          cd backend
          tar -czf ../vocali-backend-$TIMESTAMP.tar.gz . \
            --exclude='.git' \
            --exclude='uploads' \
            --exclude='temp' \
            --exclude='*.log' \
            --exclude='coverage' \
            --exclude='tests' \
            --exclude='*.test.js' || {
            echo "❌ TAR creation failed with exit code $?"
            exit 1
          }
          cd ..

          if [ -f "vocali-backend-$TIMESTAMP.tar.gz" ]; then
            echo "✅ Package created successfully: vocali-backend-$TIMESTAMP.tar.gz"
            ls -la vocali-backend-*.tar.gz
          else
            echo "❌ Package file not found after creation"
            ls -la
            exit 1
          fi

          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV

      - name: Upload to S3 for deployment
        run: |
          echo "Uploading package: vocali-backend-$TIMESTAMP.tar.gz"
          aws s3 cp vocali-backend-$TIMESTAMP.tar.gz s3://${{ vars.S3_DEPLOYMENT_BUCKET }}/vocali-backend-$TIMESTAMP.tar.gz
          echo "✅ Package uploaded: vocali-backend-$TIMESTAMP.tar.gz"

      # Opción adicional: Deploy directo a EC2 usando CodeDeploy
      - name: Trigger CodeDeploy (if configured)
        run: |
          if [ -n "${{ vars.CODEDEPLOY_APPLICATION }}" ]; then
            echo "Triggering CodeDeploy with package: vocali-backend-$TIMESTAMP.tar.gz"
            aws deploy create-deployment \
              --application-name ${{ vars.CODEDEPLOY_APPLICATION }} \
              --deployment-group-name ${{ vars.CODEDEPLOY_GROUP }} \
              --s3-location bucket=${{ vars.S3_DEPLOYMENT_BUCKET }},key=vocali-backend-$TIMESTAMP.tar.gz,bundleType=tgz \
              --description "Auto deployment from GitHub Actions - develop branch"
            echo "✅ CodeDeploy deployment triggered"
          else
            echo "⚠️ CodeDeploy not configured, manual deployment required"
          fi

      - name: Deployment complete
        run: |
          echo "🚀 Backend deployment package created successfully!"
          echo "📦 Package location: s3://${{ vars.S3_DEPLOYMENT_BUCKET }}"
          echo "📡 Monitor deployment in AWS Console or EC2 instance"
          echo "🔍 Check logs: ssh to EC2 and run 'pm2 logs vocali-backend'"
